[workspace]
resolver = "3"
members = ["exc00", "exc01", "exc02", "exc03", "exc04", "exc05", "exc06", "exc07", "exc08", "exc09", "exc10", "exc11", "exc12", "exc13", "exc14", "exc15", "exc16", "exc17", "exc18", "exc19", "exc20", "exc21", "exc22", "exc23", "exc24", "exc25", "exc26"]
